version: "3.8"
services:
  mysite_app:
    container_name: mysite_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - mysite_db
    networks:
      - app_network

  mysite_nginx:
    container_name: mysite_nginx
    user: root
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    ports:
      - 8000:80
      - 8443:443
    depends_on:
      - mysite_app
    environment:
      NGINX_FPM_HOST: mysite_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  mysite_db:
    container_name: mysite_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysite
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
